name: golang CI workflow
on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      - '**.go'
      - 'Dockerfile'
      - '**.yaml'
  pull_request:
    branches:
      - 'main'
      - 'dev'
    paths:
      - '**.go'
      - 'Dockerfile'
      - '**.yaml'
env:
  # Define container name
  CONTAINER_NAME: odlux-agent
jobs:
  #test:
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      golang-version: ["1.14"]
  #  steps:
  #    - name: checkout
  #      uses: actions/checkout@v3
  #    - name: Set up Golang ${{ matrix.golang-version }}
  #      uses: actions/setup-go@v3
  #      with:
  #        go-version: ${{ matrix.golang-version }}          
  #    - name: Run unit tests
  #      working-directory: ./${{ env.TASK_MANAGER_BASE_PATH }}
  #      run: go test -v ./...
  build:
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.CONTAINER_NAME }}:v0.1
  merge-to-main:
    needs: build
    if: ${{ github.ref }} == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config --local user.email "git@github.com"
          git config --local user.name "github action"
      - name: Merge to main branch to trigger CD workflow
        run: |
          git checkout main
          git merge --no-ff dev -m "Auto-merge dev to main"